// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWDK9xEv7pocHpPmncflrdmdqJjXYBAo',
    appId: '1:795081654686:web:1772a38c7e81b836d5568f',
    messagingSenderId: '795081654686',
    projectId: 'instagram-clone-eed20',
    authDomain: 'instagram-clone-eed20.firebaseapp.com',
    storageBucket: 'instagram-clone-eed20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQznUFCxegE3OFw4vq37ctdtYlUgLzLAY',
    appId: '1:795081654686:android:4bef3a0678c33d2ed5568f',
    messagingSenderId: '795081654686',
    projectId: 'instagram-clone-eed20',
    storageBucket: 'instagram-clone-eed20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJ9WuINMKPDZhTz2dBqMnvQS2O5PxddQ',
    appId: '1:795081654686:ios:9759f05bdfc16778d5568f',
    messagingSenderId: '795081654686',
    projectId: 'instagram-clone-eed20',
    storageBucket: 'instagram-clone-eed20.appspot.com',
    iosClientId: '795081654686-p39t89iqqk9r4a79eg6qbgio28h5ckko.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
